/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.client;

import com.model.*;
import java.io.BufferedReader;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author imsil
 */
public class NewGUI extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    DataOutputStream outputDataToServer = null;
    ObjectOutputStream outputObjectToServer = null;
    DataInputStream inputDataFromServer = null;
    BufferedReader br = null;

    public NewGUI() {
            initComponents();
            txtConsumerID.setText("");
            txtFirstName.setText("");
            txtLastName.setText("");
            txtCity.setText("");
            txtBillAmount.setText("");
            txtDueDate.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtConsumerID = new javax.swing.JTextField();
        txtFirstName = new javax.swing.JTextField();
        txtLastName = new javax.swing.JTextField();
        txtCity = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtBillAmount = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtDueDate = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnSubmit = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();

        jLabel6.setText("City");

        jLabel7.setText("Due Date");

        txtConsumerID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtConsumerIDActionPerformed(evt);
            }
        });

        txtLastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLastNameActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Consumer Form");

        jLabel2.setText("Consumer ID");

        txtDueDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDueDateActionPerformed(evt);
            }
        });
        txtDueDate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                enter(evt);
            }
        });

        jLabel3.setText("First Name");

        jLabel4.setText("Last Name");

        jLabel5.setText("Bill Amount");

        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel7)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addGap(83, 83, 83)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtConsumerID, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                            .addComponent(txtCity)
                            .addComponent(txtBillAmount)
                            .addComponent(txtDueDate)
                            .addComponent(btnClear)
                            .addComponent(txtFirstName)
                            .addComponent(txtLastName)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(btnSubmit))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtConsumerID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtBillAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtDueDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSubmit)
                    .addComponent(btnClear))
                .addGap(8, 8, 8))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtConsumerIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtConsumerIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtConsumerIDActionPerformed

    private void txtLastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLastNameActionPerformed

    private void txtDueDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDueDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDueDateActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed

        boolean flag1, flag2, flag3, flag4, flag5, flag6;
        flag1 = flag2 = flag3 = flag4 = flag5 = flag6 = false;
        Consumer c = new Consumer();
        try {
            c.setConsumerID(Long.parseLong(txtConsumerID.getText()));
            if (!(Long.parseLong(txtConsumerID.getText()) > 9999999999L && Long.parseLong(txtConsumerID.getText()) < 100000000000L)) {
                throw new ValidConsumerIDException();
            }
            flag1 = true;
        } catch (NumberFormatException nfe) {
            flag1 = false;
            JOptionPane.showMessageDialog(null, "Consumer ID is mandatory");
        } catch (ValidConsumerIDException vc) {
            flag1 = false;
            JOptionPane.showMessageDialog(null, vc.getMessage());
        } catch (Exception ex) {
            flag1 = false;
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
        try {
            c.setFirstName(txtFirstName.getText().toUpperCase());
            flag2 = true;
        } catch (ValidNameException ex) {
            flag2 = false;
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
        try {
            c.setLastName(txtLastName.getText().toUpperCase());
            flag3 = true;
        } catch (ValidNameException ex) {
            flag3 = false;
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
        try {
            c.setCity(txtCity.getText().toUpperCase());
            flag4 = true;
        } catch (ValidNameException ex) {
            flag4 = false;
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
        try {
            c.setBillAmount(Double.parseDouble(txtBillAmount.getText()));
            flag5 = true;
        } catch (NumberFormatException nfe) {
            flag5 = false;
            JOptionPane.showMessageDialog(null, "Bill Amount must be numeric and cannot be left blank");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Bill Amount should be non negative");
        }
        try {
            DateFormat dateFormat = new SimpleDateFormat("dd/MM/yy");
            Date date = dateFormat.parse(txtDueDate.getText());
            c.setDueDate(date);
            flag6 = true;
        } catch (ParseException ex) {
            flag6 = false;
            JOptionPane.showMessageDialog(null, "Date must be dd/mm/yy format and cannot be left blank");
        } catch (NullPointerException npe) {
            flag6 = false;
            JOptionPane.showMessageDialog(null, npe.getMessage());
        }

        if (flag1 && flag2 && flag3 && flag4 && flag5 && flag6) {
            try {
                //Create an output data stream to server
            outputDataToServer = IOUtility.getDataOutputStream();
            //Create an output Object stream to the server
            outputObjectToServer = IOUtility.getObjectOutputStream();
            //Create an input Data stream from server
            inputDataFromServer = IOUtility.getDataInputStream();

            br = IOUtility.getBufferedReader();
                //Send data to server
                outputDataToServer.writeInt(1);
                outputDataToServer.flush();
                // Create a Consumer object and send to the server
                outputObjectToServer.writeObject(c);
                outputObjectToServer.flush();
                String msg = br.readLine().trim();
                JOptionPane.showMessageDialog(null, msg);
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(null, ex);
            }catch (UnableToConnectException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
        }
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        txtConsumerID.setText("");
        txtFirstName.setText("");
        txtLastName.setText("");
        txtCity.setText("");
        txtBillAmount.setText("");
        txtDueDate.setText("");
    }//GEN-LAST:event_btnClearActionPerformed

    private void enter(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_enter
        // TODO add your handling code here:
        if (evt.getKeyCode() == 10) {
            btnSubmitActionPerformed(null);
        }
    }//GEN-LAST:event_enter


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtBillAmount;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtConsumerID;
    private javax.swing.JTextField txtDueDate;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtLastName;
    // End of variables declaration//GEN-END:variables

    public void setTxtBillAmount(String txtBillAmount) {
        this.txtBillAmount.setText(txtBillAmount);
    }

    public void setTxtCity(String txtCity) {
        this.txtCity.setText(txtCity);
    }

    public void setTxtConsumerID(String txtConsumerID) {
        this.txtConsumerID.setText(txtConsumerID);
    }

    public void setTxtDueDate(String txtDueDate) {
        this.txtDueDate.setText(txtDueDate);
    }

    public void setTxtFirstName(String txtFirstName) {
        this.txtFirstName.setText(txtFirstName);
    }

    public void setTxtLastName(String txtLastName) {
        this.txtLastName.setText(txtLastName);
    }

}
